version: '3.8'

services:
  # PostgreSQL para Analytics Service
  postgres:
    image: postgres:15
    container_name: ${DOCKER_CONTAINER_PREFIX}_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK}



  # Redis para Notification Service
  redis:
    image: redis:7.2-alpine
    container_name: ${DOCKER_CONTAINER_PREFIX}_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - ${DOCKER_NETWORK}

  # RabbitMQ para Event Bus
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ${DOCKER_CONTAINER_PREFIX}_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ${DOCKER_NETWORK}

  # MottoSprint - Aplicação Principal
  mottosprint:
    build:
      context: ./MottoSprint
      dockerfile: Dockerfile
    container_name: ${DOCKER_CONTAINER_PREFIX}_mottosprint
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=redis:${REDIS_PORT}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=${RABBITMQ_USERNAME}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - Email__SmtpHost=${SMTP_HOST}
      - Email__SmtpPort=${SMTP_PORT}
      - Email__Username=${SMTP_USERNAME}
      - Email__Password=${SMTP_PASSWORD}
    ports:
      - "${MOTTOSPRINT_PORT:-5000}:80"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  estacionamento-network:
    driver: bridge